overrides:
  # JSON with comments and trailing commas
  - files:
      - ".vscode/*.json"
      - "benchmarks/*.json"
    options:
      parser: json5
      quoteProps: preserve
      singleQuote: false
