version: 2

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

formats:
    - htmlzip

build:
    image: testing

python:
    version: 3.9
    install:
        - method: pip
          path: .
          extra_requirements:
              - docs
