# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        # TODO: remove UV_CONSTRAINT once hatch is compatible with virtualenv 21+ (pypa/hatch#2193)
        - UV_CONSTRAINT=$READTHEDOCS_REPOSITORY_PATH/.github/uv-constraints.txt uvx hatch run docs:build
        - mv docs/_build $READTHEDOCS_OUTPUT

submodules:
  include: [docs/notebooks]
  recursive: true
