language: python

os: linux

dist: focal

python:
    - "3.6"
    - "3.7"
    - "3.8"

jobs:
  fast_finish: true
  include:
    - name: "Code analysis"
      os: linux
      python: "3.8"
      script:
        - pip install -e."[dev]" && pre-commit run --all-files
      after_success: skip
      after_failure: skip

    - name: "Python 3.6.5 on macOS"
      language: bash
      os: osx
      osx_image: xcode9.4
      env:
        - PYTHON_VERSION=3.6.5

    - name: "Python 3.7.3 on macOS"
      language: bash
      os: osx
      osx_image: xcode10.2
      env:
        - PYTHON_VERSION=3.7.3

    # TODO: macOS 3.8 (through brew)

install: pip install tox-travis

script: tox
