"""Plotting test conftest.

When SQUIDPY_USE_SDATAPLOT=1 is set, the legacy reference-image suite in
test_spatial_static.py compares against baselines that were generated by the
legacy matplotlib renderer. The sdata-plot delegation produces different
pixels by design, so the comparisons fail noisily. Skip them under the flag
and point users at the new-path suite.
"""

from __future__ import annotations

import os

import pytest


def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    if os.environ.get("SQUIDPY_USE_SDATAPLOT", "").lower() not in {"1", "true", "yes", "on"}:
        return
    skip_marker = pytest.mark.skip(
        reason=(
            "Skipped under SQUIDPY_USE_SDATAPLOT=1: legacy reference-image baselines target "
            "the matplotlib renderer. Use tests/plotting/test_spatial_scatter_sdataplot.py "
            "for the delegation pipeline."
        )
    )
    for item in items:
        if "test_spatial_static.py" in str(item.fspath) and "TestSpatialStatic" in item.nodeid:
            item.add_marker(skip_marker)
