name: Question
description: Ask a question about Squidpy
labels: question
body:
    - type: textarea
      id: question
      attributes:
          label: Question
          description: Ask a question about Squidpy
      validations:
          required: true
