"""``align_stalign_slice`` and ``rasterize_points``, through their public entry points.

Container access and write-back only: the numerics are covered by ``test_stalign.py`` and
compared against the original STalign out of band, from the reference bundle generated by
https://github.com/theislab/squidpy-ports.
"""

from __future__ import annotations

import numpy as np
import pytest

pytest.importorskip("jax")
pytest.importorskip("spatialdata")

import anndata as ad  # noqa: E402
import pandas as pd  # noqa: E402
from spatialdata import SpatialData  # noqa: E402
from spatialdata.models import Image2DModel, Image3DModel, PointsModel  # noqa: E402
from spatialdata.transformations import Scale, Translation  # noqa: E402
from spatialdata.transformations import Sequence as TransformSequence  # noqa: E402

from squidpy.experimental.im import rasterize_points  # noqa: E402
from squidpy.experimental.tl import StalignSliceResult, align_stalign_slice  # noqa: E402

#: Rank-3 settings small enough to stay fast, large enough to run the whole path.
_TINY = {"a": 3.0, "expand": 1.25, "nt": 1, "niter": 1, "epV": 1.0}
_VOXEL = 2.0


def _volume(nz: int = 7, ny: int = 11, nx: int = 13) -> np.ndarray:
    zz, yy, xx = np.meshgrid(np.arange(nz), np.arange(ny), np.arange(nx), indexing="ij")
    blob = np.exp(-(((zz - nz / 2) / 2.0) ** 2 + ((yy - ny / 2) / 3.0) ** 2 + ((xx - nx / 2) / 3.5) ** 2))
    return np.stack([blob, (blob - blob.mean()) ** 2])


def _sdata(*, ref_translation: tuple[float, float, float] | None = None) -> SpatialData:
    volume = _volume()
    transformations = [Scale([_VOXEL, _VOXEL, _VOXEL], axes=("z", "y", "x"))]
    if ref_translation is not None:
        transformations.append(Translation(list(ref_translation), axes=("z", "y", "x")))
    sdata = SpatialData(
        images={
            "atlas": Image3DModel.parse(
                volume,
                dims=("c", "z", "y", "x"),
                transformations={"global": TransformSequence(transformations)},
            ),
            "section": Image2DModel.parse(
                volume[0, 3][None],
                dims=("c", "y", "x"),
                transformations={"global": Scale([_VOXEL, _VOXEL], axes=("y", "x"))},
            ),
        }
    )
    coords = np.column_stack([np.linspace(2.0, 20.0, 12), np.linspace(2.0, 16.0, 12)])
    table = ad.AnnData(np.zeros((12, 1)), obsm={"spatial": coords})
    sdata.tables["cells"] = table
    return sdata


def _fit(sdata: SpatialData, **kwargs):
    return align_stalign_slice(sdata, image_key=("atlas", "section"), **{**_TINY, **kwargs})


def test_returns_the_fit_when_nothing_is_written() -> None:
    result = _fit(_sdata())
    assert isinstance(result, StalignSliceResult)


def test_physical_axes_come_from_the_element_transformation() -> None:
    """The element's own scale supplies the units, so nothing has to be restated.

    A ``*_scale`` argument could disagree with the container; reading the transformation
    cannot.
    """
    result = _fit(_sdata())
    np.testing.assert_allclose(np.asarray(result.ref_axes[0]), np.arange(7) * _VOXEL)
    np.testing.assert_allclose(np.asarray(result.query_axes[0]), np.arange(11) * _VOXEL)


def test_element_translation_shifts_the_axes() -> None:
    """A translation on the element moves the frame the fit works in."""
    result = _fit(_sdata(ref_translation=(100.0, 10.0, 20.0)))
    np.testing.assert_allclose(np.asarray(result.ref_axes[0]), np.arange(7) * _VOXEL + 100.0)
    np.testing.assert_allclose(np.asarray(result.ref_axes[2]), np.arange(13) * _VOXEL + 20.0)


def test_rotation_in_the_transformation_is_refused() -> None:
    """Per-axis coordinates cannot express a rotation, so guessing would be wrong."""
    from spatialdata.transformations import Affine

    sdata = _sdata()
    rotation = np.eye(4)
    rotation[1:3, 1:3] = [[0.0, -1.0], [1.0, 0.0]]
    sdata.images["atlas"] = Image3DModel.parse(
        _volume(),
        dims=("c", "z", "y", "x"),
        transformations={"global": Affine(rotation, input_axes=("z", "y", "x"), output_axes=("z", "y", "x"))},
    )
    with pytest.raises(ValueError, match="rotation or shear"):
        _fit(sdata)


def test_write_back_adds_three_columns_to_a_copy() -> None:
    sdata = _sdata()
    out = _fit(sdata, table_key="cells", key_added="atlas_xyz")

    assert isinstance(out, SpatialData)
    assert out.tables["cells"].obsm["atlas_xyz"].shape == (12, 3)
    assert "atlas_xyz" not in sdata.tables["cells"].obsm, "inplace=False must not touch the input"


def test_write_back_inplace_returns_none() -> None:
    sdata = _sdata()
    assert _fit(sdata, table_key="cells", key_added="atlas_xyz", inplace=True) is None
    assert sdata.tables["cells"].obsm["atlas_xyz"].shape == (12, 3)


def test_key_added_needs_a_table_key() -> None:
    """Which table holds the cells is not inferable, and guessing wrong is silent."""
    with pytest.raises(ValueError, match="table_key"):
        _fit(_sdata(), key_added="atlas_xyz")


def test_inplace_without_key_added_is_refused() -> None:
    with pytest.raises(ValueError, match="nothing to write"):
        _fit(_sdata(), inplace=True)


def test_a_two_dimensional_reference_is_refused() -> None:
    """A ``(c, y, x)`` section as the reference reads as a one-voxel-deep volume.

    Left unguarded that fit "succeeds": the z axis has a single sample, so its spacing
    comes out as zero and every interpolated value is silently inf or nan. There is no
    out-of-plane information to fit either way -- ``align_stalign_image`` is the 2D path.
    """
    sdata = _sdata()
    sdata.images["flat"] = Image2DModel.parse(
        _volume()[0, 3][None],
        dims=("c", "y", "x"),
        transformations={"global": Scale([_VOXEL, _VOXEL], axes=("y", "x"))},
    )
    with pytest.raises(ValueError, match="at least two samples along `z`"):
        align_stalign_slice(sdata, image_key=("flat", "section"), **_TINY)


# --------------------------------------------------------------------------------------
# rasterize_points
# --------------------------------------------------------------------------------------


def _points_sdata(n: int = 400) -> tuple[SpatialData, np.ndarray]:
    rng = np.random.default_rng(0)
    coords = np.column_stack([rng.normal(50.0, 12.0, n), rng.normal(-30.0, 9.0, n)])
    sdata = SpatialData(points={"cells": PointsModel.parse(pd.DataFrame({"x": coords[:, 0], "y": coords[:, 1]}))})
    return sdata, coords


def test_rasterize_points_conserves_mass() -> None:
    """Every point contributes exactly one unit, wherever it sits.

    This is the property that makes the raster a density rather than an approximation of
    one, and it is what a blur with plain zero padding silently breaks near the border.
    """
    sdata, coords = _points_sdata()
    image = rasterize_points(sdata, "cells", dx=3.0, blur=1.0)
    assert float(np.asarray(image).sum()) == pytest.approx(coords.shape[0], rel=1e-9)


def test_rasterize_points_makes_one_channel_per_blur() -> None:
    sdata, _ = _points_sdata()
    image = rasterize_points(sdata, "cells", dx=4.0, blur=(2.0, 1.0, 0.5))
    assert np.asarray(image).shape[0] == 3
    assert image.dims == ("c", "y", "x")


def test_rasterize_points_is_registered_where_the_points_are() -> None:
    """The raster has to land on the points, not at the origin.

    Mapping the image's own corner pixel through its transformation must reproduce the
    grid origin the rasteriser chose, which sits a margin below the points' minimum.
    """
    from spatialdata.transformations import get_transformation

    sdata, coords = _points_sdata()
    dx = 3.0
    image = rasterize_points(sdata, "cells", dx=dx, blur=1.0, expand=1.1)
    matrix = np.asarray(
        get_transformation(image, to_coordinate_system="global").to_affine_matrix(
            input_axes=("y", "x"), output_axes=("y", "x")
        )
    )

    origin = matrix @ np.array([0.0, 0.0, 1.0])
    span = np.ptp(coords, axis=0)
    centre = (coords.min(axis=0) + coords.max(axis=0)) / 2.0
    expected = centre - span * 1.1 / 2.0  # the rasteriser's own grid origin, in `(x, y)`

    np.testing.assert_allclose(origin[0], expected[1], atol=dx)
    np.testing.assert_allclose(origin[1], expected[0], atol=dx)
    np.testing.assert_allclose(np.diag(matrix)[:2], [dx, dx])


def test_rasterize_points_key_added_stores_the_image() -> None:
    sdata, _ = _points_sdata()
    assert rasterize_points(sdata, "cells", key_added="density", dx=4.0) is sdata.images["density"]


def test_rasterize_points_reports_a_missing_element() -> None:
    sdata, _ = _points_sdata()
    with pytest.raises(KeyError, match="no such points element"):
        rasterize_points(sdata, "nope")


def test_rasterize_points_needs_no_jax() -> None:
    """It is a plain image primitive, so the optional JAX extra must not gate it."""
    import subprocess
    import sys

    code = (
        "import sys; import squidpy.experimental.im as m; "
        "assert m.rasterize_points is not None; "
        "sys.exit(1 if 'jax' in sys.modules else 0)"
    )
    assert subprocess.run([sys.executable, "-c", code], check=False).returncode == 0
