"""STalign behaviour, exercised through the public ``align_stalign_*`` functions.

Everything here goes through :mod:`squidpy.experimental.tl`: the estimators and the JAX
solver under it are private, so reaching past the public functions would test paths no
caller can use. Tiny fixtures with ``niter=1`` keep most of these fast -- they check
result semantics (shapes, the transform, the energy trace), not solver quality.

The block at the bottom does check solver quality, cheaply. It is the only guard here
against a numerical regression: the full comparison against the original STalign runs
out of band, from the reference bundle generated by
https://github.com/theislab/squidpy-ports.
"""

from __future__ import annotations

import numpy as np
import pytest

pytest.importorskip("jax")

from squidpy.experimental.tl import StalignResult, align_stalign_image, align_stalign_obs
from tests.experimental.conftest import ALIGN_PTS as _PTS
from tests.experimental.conftest import TINY_SOLVER as _TINY
from tests.experimental.conftest import make_adata as _adata


def _fit(ref: np.ndarray = _PTS, query: np.ndarray = _PTS, **kwargs) -> StalignResult:
    """Fit through the public point-cloud function and hand back the result."""
    result = align_stalign_obs(_adata(ref), _adata(query), **{**_TINY, **kwargs})
    assert isinstance(result, StalignResult)
    return result


def _sdata_image(ref: np.ndarray, query: np.ndarray):
    sd = pytest.importorskip("spatialdata")
    from spatialdata.models import Image2DModel

    def parse(arr: np.ndarray):
        arr = np.asarray(arr, dtype=float)
        return Image2DModel.parse(arr[None] if arr.ndim == 2 else arr, dims=("c", "y", "x"))

    return sd.SpatialData(images={"ref": parse(ref), "query": parse(query)})


# --- result semantics ------------------------------------------------------------------


def test_fit_returns_a_diffeomorphism() -> None:
    result = _fit()

    assert result.aligned_points.shape == _PTS.shape
    assert np.all(np.isfinite(np.asarray(result.aligned_points)))
    assert result.affine.shape == (3, 3)
    assert result.velocity.ndim == 4
    assert result.match_weights is not None
    assert result.artifact_weights is not None
    assert result.background_weights is not None
    assert result.energies is not None
    assert result.n_iter == 1


def test_transform_matches_aligned_points() -> None:
    result = _fit()
    np.testing.assert_allclose(np.asarray(result.transform(_PTS)), np.asarray(result.aligned_points), atol=1e-5)


def test_transform_accepts_arbitrary_points() -> None:
    assert np.asarray(_fit().transform(np.zeros((1, 2)))).shape == (1, 2)


def test_transform_backward_inverts_forward() -> None:
    result = _fit()
    forward = result.transform(_PTS, direction="forward")
    roundtrip = result.transform(forward, direction="backward")
    np.testing.assert_allclose(np.asarray(roundtrip), _PTS, atol=1e-3)


def test_transform_rejects_non_2d() -> None:
    with pytest.raises(ValueError, match=r"Expected an \(N, 2\)"):
        _fit().transform(np.zeros((5, 3)))


def test_default_dtype_is_single_precision() -> None:
    """The solver runs in JAX's active precision, single unless x64 is enabled.

    ``jax.config.update`` is process-global, so any module imported here that enabled
    x64 would silently flip every test to float64 -- and the documented default that
    ``align_stalign_obs``'s Notes warn about would stop holding.
    """
    import jax
    import jax.numpy as jnp

    expected = jnp.float64 if jax.config.jax_enable_x64 else jnp.float32
    assert _fit().affine.dtype == expected


# --- initialisation -------------------------------------------------------------------


def test_fit_with_landmark_initialisation() -> None:
    landmarks = _PTS[:3]
    result = _fit(landmarks_ref=landmarks, landmarks_query=landmarks)
    assert result.aligned_points.shape == _PTS.shape


def test_explicit_initial_affine_is_read_in_xy() -> None:
    affine = np.array([[1.0, 0.0, 3.0], [0.0, 1.0, 4.0], [0.0, 0.0, 1.0]])

    result = _fit(initial_affine=affine, niter=0)

    np.testing.assert_allclose(np.asarray(result.aligned_points), _PTS + np.array([3.0, 4.0]), atol=1e-5)


def test_zero_iterations_evaluates_the_initial_state() -> None:
    """``niter=0`` means "evaluate and stop", not a crash.

    The energy and the transformed landmarks used to be bound only inside the loop, so
    the return statement read unbound locals.
    """
    result = _fit(niter=0)

    assert result.velocity.shape[0] == 1
    assert result.affine.shape == (3, 3)


def test_non_finite_landmarks_are_rejected() -> None:
    bad = np.array([[0.0, 0.0], [1.0, np.nan], [2.0, 2.0]])
    with pytest.raises(ValueError, match="contain only finite values"):
        _fit(landmarks_ref=bad, landmarks_query=bad)


def test_landmarks_must_be_xy_pairs() -> None:
    with pytest.raises(ValueError, match=r"to be a sequence of \(x, y\) pairs"):
        _fit(landmarks_ref=np.zeros((5, 3)), landmarks_query=np.zeros((5, 3)))


# --- mixture means --------------------------------------------------------------------


def test_fixed_mixture_means_accepted_per_channel() -> None:
    rgb = np.zeros((3, 8, 8))
    rgb[:, 2:6, 2:6] = 1.0

    result = align_stalign_image(
        _sdata_image(rgb, rgb),
        image_key=("ref", "query"),
        muA=np.ones(3),
        muB=np.zeros(3),
        niter=1,
        a=2.0,
        nt=1,
    )

    assert isinstance(result, StalignResult)
    assert np.all(np.isfinite(np.asarray(result.affine)))


def test_wrong_mixture_mean_shape_is_rejected() -> None:
    # `blur` is a scalar here, so the density raster has a single channel.
    with pytest.raises(ValueError, match=r"Expected `muA` to have shape \(1,\)"):
        _fit(muA=np.ones(3))


# --- images ---------------------------------------------------------------------------


def test_explicit_axes_warp_both_directions() -> None:
    image = np.arange(20, dtype=float).reshape(4, 5)
    axes = (np.linspace(10.0, 13.0, 4), np.linspace(20.0, 24.0, 5))

    result = align_stalign_image(
        _sdata_image(image, image),
        image_key=("ref", "query"),
        query_axes=axes,
        ref_axes=axes,
        niter=0,
        a=1.0,
        nt=1,
    )
    assert isinstance(result, StalignResult)

    np.testing.assert_allclose(np.asarray(result.warp_image(image, direction="forward"))[0], image, atol=1e-5)
    np.testing.assert_allclose(np.asarray(result.warp_image(image, direction="backward"))[0], image, atol=1e-5)
    assert result.deformation_grid(direction="forward").shape == (2, 4, 5)
    assert result.deformation_grid(direction="backward").shape == (2, 4, 5)


# --- solver quality, cheap enough to run on every PR ----------------------------------

# A cloud with enough structure to be alignable, and a query that is a known rigid
# transform of it. Small enough that a few hundred iterations run in about a second.
_SOLVE = {"dx": 8.0, "blur": 1.0, "a": 40.0, "nt": 3, "epV": 5e2}


def _blobs(seed: int = 0) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return np.concatenate(
        [
            rng.normal(scale=(18.0, 11.0), size=(120, 2)),
            rng.normal(scale=8.0, size=(60, 2)) + np.array([55.0, 34.0]),
        ]
    )


def _rotated(angle: float = 0.12) -> tuple[np.ndarray, np.ndarray]:
    ref = _blobs()
    rotation = np.array([[np.cos(angle), -np.sin(angle)], [np.sin(angle), np.cos(angle)]])
    return ref, ref @ rotation.T + np.array([6.0, -4.0])


def _solve(**kwargs) -> StalignResult:
    ref, query = _rotated()
    result = align_stalign_obs(_adata(ref), _adata(query), **{**_SOLVE, **kwargs})
    assert isinstance(result, StalignResult)
    return result


def test_energy_trace_is_reported() -> None:
    """Without this a caller cannot tell a converged run from a diverged one."""
    result = _solve(niter=30)

    assert result.energies.shape == (30,)
    assert int(result.n_iter) == 30
    assert np.all(np.isfinite(np.asarray(result.energies)))


def test_early_stopping_is_off_by_default() -> None:
    """The shipped default must leave early stopping off and run every iteration."""
    plain = _solve(niter=40)
    explicit = _solve(niter=40, tol=None)

    assert int(plain.n_iter) == 40
    np.testing.assert_array_equal(np.asarray(plain.velocity), np.asarray(explicit.velocity))


def test_early_stopping_never_fires_before_the_weights_switch_on() -> None:
    """The objective changes definition at iteration 50 and its value jumps upward.

    A stopping rule that compares across that boundary sees the jump as "no longer
    improving" and quits immediately, which is what a naive implementation does.
    """
    # The one implementation detail this file reaches for: the iteration the mixture-weight
    # E step engages. Hard-coding 50 here would silently pass if the solver ever moved it.
    from squidpy.experimental.tl._align._stalign_impl._core import MIXTURE_E_STEP_START

    # A tolerance so loose it would stop at the first opportunity.
    result = _solve(niter=400, tol=1e9, patience=25)

    assert int(result.n_iter) >= MIXTURE_E_STEP_START + 2 + 25
    trace = np.asarray(result.energies)
    assert trace[MIXTURE_E_STEP_START + 1] > trace[MIXTURE_E_STEP_START], (
        "expected the objective to jump when the mixture-weight E step engages"
    )


def test_early_stopping_shortens_the_run() -> None:
    # Loose enough to fire on this fixture but not at the first opportunity: it stops
    # around iteration 157 of 400, whereas tol=1e-2 keeps improving through all 400.
    stopped = _solve(niter=400, tol=1e-1, patience=25)

    ran = int(stopped.n_iter)
    assert 77 < ran < 400
    # Iterations that never ran stay NaN rather than reporting a bogus energy.
    trace = np.asarray(stopped.energies)
    assert np.all(np.isfinite(trace[:ran])) and np.all(np.isnan(trace[ran:]))


def test_energy_decreases_with_more_iterations() -> None:
    """More iterations must buy a lower objective. Catches a broken gradient or step."""
    first = float(np.asarray(_solve(niter=1).energies)[-1])
    later = float(np.asarray(_solve(niter=60).energies)[-1])

    assert later < first, f"energy did not decrease: {first} -> {later}"


def test_recovers_a_known_rigid_transform() -> None:
    """The query is a known rotation+translation of the reference; alignment must undo it.

    Asserts on the median rather than the mean: rasterisation at ``dx=8`` quantises the
    clouds, so a handful of points on the sparse outskirts stay poorly matched however
    good the fit is.
    """
    ref, query = _rotated()

    result = _solve(niter=250)
    residual = np.linalg.norm(np.asarray(result.aligned_points) - ref, axis=1)

    before = np.median(np.linalg.norm(query - ref, axis=1))
    after = float(np.median(residual))
    assert after < before / 2.0, f"alignment barely improved: median {before:.2f} -> {after:.2f}"
    assert after < _SOLVE["dx"], f"median residual {after:.2f} exceeds one grid cell ({_SOLVE['dx']})"


# --------------------------------------------------------------------------------------
# Section into a reference volume
# --------------------------------------------------------------------------------------

#: Smallest rank-3 settings that still exercise the full code path. `a` has to stay small
#: enough that the velocity grid keeps at least two samples on every axis.
_TINY_SLICE = {"a": 3.0, "expand": 1.25, "nt": 1, "niter": 1, "epV": 1.0}


def _volume(nz: int = 7, ny: int = 11, nx: int = 13) -> np.ndarray:
    """A two-channel reference volume whose structure genuinely varies with ``z``."""
    zz, yy, xx = np.meshgrid(np.arange(nz), np.arange(ny), np.arange(nx), indexing="ij")
    blob = np.exp(-(((zz - nz / 2) / 2.0) ** 2 + ((yy - ny / 2) / 3.0) ** 2 + ((xx - nx / 2) / 3.5) ** 2))
    return np.stack([blob, (blob - blob.mean()) ** 2])


def _section(volume: np.ndarray, index: int = 3) -> np.ndarray:
    """One channel of one slice, which is what a real section looks like: 1 channel."""
    return volume[0, index][None]


def _slice_fit(**kwargs):
    from squidpy.experimental.tl._align._stalign import fit_stalign_slice

    volume = _volume()
    return fit_stalign_slice(volume, _section(volume), **{**_TINY_SLICE, **kwargs})


def test_slice_fit_returns_a_rank_three_deformation() -> None:
    """Shapes first: a (4, 4) affine, a velocity with three spatial axes and 3 components."""
    from squidpy.experimental.tl import StalignSliceResult

    fit = _slice_fit()

    assert isinstance(fit, StalignSliceResult)
    assert np.asarray(fit.affine).shape == (4, 4)
    assert np.asarray(fit.velocity).ndim == 5
    assert np.asarray(fit.velocity).shape[-1] == 3
    assert len(fit.velocity_grid) == 3
    assert len(fit.ref_axes) == 3 and len(fit.query_axes) == 2


def test_slice_accepts_mismatched_channel_counts() -> None:
    """A 2-channel reference against a 1-channel section is upstream's own recipe.

    The contrast transform fits one to the other, so requiring equal counts would reject
    the case the whole feature exists for.
    """
    volume = _volume()
    assert volume.shape[0] == 2
    fit = _slice_fit()
    assert np.isfinite(float(np.asarray(fit.energies)[0]))


def test_slice_transform_lifts_and_reverses_axes() -> None:
    """``(N, 2)`` in ``(x, y)`` out to ``(N, 3)`` in ``(x, y, z)``, at the same z."""
    fit = _slice_fit(initial_slice=3)
    points = np.array([[0.0, 0.0], [1.5, -2.0], [-3.0, 2.5]])

    out = np.asarray(fit.transform(points))

    assert out.shape == (3, 3)
    # A flat section maps into one plane, so with no deformation every z agrees.
    assert np.allclose(out[:, 2], out[0, 2])


def test_slice_transform_rejects_wrong_shape() -> None:
    fit = _slice_fit()
    with pytest.raises(ValueError, match=r"\(N, 2\)"):
        fit.transform(np.zeros((4, 3)))


def test_slice_sample_reference_reads_the_volume() -> None:
    """``order=0`` must return exact stored values; ``order=1`` may interpolate."""
    volume = _volume()
    fit = _slice_fit(initial_slice=3)
    labels = (volume[0] > 0.5).astype(np.int16)
    points = fit.transform(np.array([[0.0, 0.0], [2.0, 1.0]]))

    ids = np.asarray(fit.sample_reference(labels, fit.ref_axes, points, order=0))
    values = np.asarray(fit.sample_reference(volume, fit.ref_axes, points, order=1))

    assert ids.shape == (2,)
    assert set(np.unique(ids)) <= {0.0, 1.0}, "nearest sampling invented an intermediate id"
    assert values.shape == (2, 2), "a channelled volume must come back channelled"


def test_slice_sample_reference_validates_its_inputs() -> None:
    fit = _slice_fit()
    with pytest.raises(ValueError, match="three"):
        fit.sample_reference(_volume(), fit.ref_axes[:2], np.zeros((2, 3)))
    with pytest.raises(ValueError, match=r"\(N, 3\)"):
        fit.sample_reference(_volume(), fit.ref_axes, np.zeros((2, 2)))
    with pytest.raises(ValueError, match=r"\(z, y, x\)"):
        fit.sample_reference(np.zeros((4, 4)), fit.ref_axes, np.zeros((2, 3)))


def test_slice_affine_xyz_is_the_reversed_affine() -> None:
    """``affine_xyz`` must be the same map, read in the caller's axis order.

    Checked by agreeing with ``transform`` on a point, not by comparing matrices: the
    point is that the two conventions describe one transformation.
    """
    fit = _slice_fit()
    affine = np.asarray(fit.affine_xyz)
    assert affine.shape == (4, 4)
    np.testing.assert_allclose(affine[3], [0.0, 0.0, 0.0, 1.0], atol=1e-12)

    # The affine alone, applied backwards, is `transform` when the velocity is zero.
    fit.velocity = np.zeros_like(np.asarray(fit.velocity))
    point_xy = np.array([[1.25, -0.75]])
    lifted = np.array([1.25, -0.75, 0.0, 1.0])
    expected = np.linalg.inv(affine) @ lifted

    np.testing.assert_allclose(np.asarray(fit.transform(point_xy))[0], expected[:3], rtol=1e-6, atol=1e-6)


def test_slice_initial_affine_excludes_the_shorthand() -> None:
    """The two initialisation routes would silently override each other."""
    with pytest.raises(ValueError, match="mutually exclusive"):
        _slice_fit(initial_affine=np.eye(4), initial_rotation=0.5)


def test_slice_initial_slice_is_bounds_checked() -> None:
    with pytest.raises(ValueError, match="outside the reference"):
        _slice_fit(initial_slice=99)


def test_slice_mixture_means_are_per_section_channel() -> None:
    """``muA`` has one entry per *section* channel, not per reference channel.

    Upstream's notebook passes three against a single-channel target and lets broadcasting
    sum three identical terms, which quietly makes its artifact scale ``sigmaA/sqrt(3)``.
    Raising is the honest behaviour, and this pins that the length checked is the
    section's -- 1 here -- rather than the reference's 2.
    """
    _slice_fit(muA=[3.0], muB=[0.0])
    with pytest.raises(ValueError, match=r"`muA` to have shape \(1,\)"):
        _slice_fit(muA=[3.0, 3.0, 3.0])


def test_slice_solver_kwargs_do_not_advertise_sigmaP() -> None:
    """Upstream's 3D path has no point term, so a ``sigmaP`` knob here would do nothing."""
    from squidpy.experimental.tl import StalignSliceSolverKwargs

    keys = StalignSliceSolverKwargs.__annotations__
    assert "sigmaP" not in keys
    assert "initial_affine" not in keys, "`initial_affine` is a named argument, not solver tuning"
    assert {"a", "niter", "sigmaR", "muA", "tol"} <= set(keys)
