name: Test notebooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # TODO: remove once hatch is compatible with virtualenv 21+ (pypa/hatch#2193)
  UV_CONSTRAINT: ${{ github.workspace }}/.github/uv-constraints.txt

jobs:
  ensure-data-is-cached:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: blob:none
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: false
          python-version: "3.14"

      - name: Restore data cache
        id: data-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: data # IMPORTANT: this will fail if scanpy.settings.datasetdir default changes
          key: data-${{ hashFiles('**/download_data.py') }}
          restore-keys: |
            data-
          enableCrossOsArchive: true

      - name: Download datasets
        # Always run to ensure any missing files are downloaded
        # (restore-keys may provide partial cache)
        run: uvx hatch run data:download

  test:
    needs: [ensure-data-is-cached]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.12"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          persist-credentials: false
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python }}

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          python-version: ${{ matrix.python }}
          cache-dependency-glob: pyproject.toml

      - name: Restore data cache
        id: data-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: data # IMPORTANT: this will fail if scanpy.settings.datasetdir default changes
          key: data-${{ hashFiles('**/download_data.py') }}
          restore-keys: |
            data-
          enableCrossOsArchive: true

      - name: Create notebooks environment
        run: uvx hatch -v env create notebooks

      - name: Test notebooks
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
          DISPLAY: :42

        run: |
          uvx hatch run notebooks:setup-squidpy-kernel
          uvx hatch run notebooks:run-notebooks
